### ISSUE TITLE
Best way to specify a default for a pydantic.HttpUrl?

### ISSUE THREAD

**Issue by abadger** [samuelcolvin/pydantic#1684]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /home/badger/.cache/pypoetry/virtualenvs/antsibull-X-j9VvlO-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Feb 26 2020, 00:00:00)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
                     platform: Linux-5.6.15-200.fc31.x86_64-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```

What is the best way to specify a default for a pydantic.HttpUrl?  I was using a literal string containing the url but when mypy or pyre checked the class, it called that an error.  After some experimentation with the HttpUrl class, I found something that worked but it seems a little verbose:
```py
import pydantic as p
class Test1(p.BaseModel):
    pypi_url: p.HttpUrl = p.HttpUrl('https://pypi.org/', scheme='https', host='pypi.org')  # Working
class Test2(p.BaseModel):
    pypi_url: p.HttpUrl = 'https://pypi.org/'  # Simple but mypy complains

```
```
$ mypy test.py                                                                                                                                                                                       (10:23:13)
test.py:5: error: Incompatible types in assignment (expression has type "str", variable has type "HttpUrl")
Found 1 error in 1 file (checked 1 source file)
```

Is there a better way to do this?

**Comment by samuelcolvin** [comment]
The best solution is to use a literal string and mute the linter.

I'm future pydantic might get a way to do this automatically, the nearest to an issue about this is probably https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/36#issuecomment-618478815

**Comment by abadger** [comment]
Thanks!

**Comment by phillipuniverse** [comment]
@abadger @samuelcolvin wouldn't the better thing to do be to assign the default through `Field`? Example:

```python
import pydantic as p

class Test2(p.BaseModel):
    pypi_url: p.HttpUrl = p.Field('https://pypi.org/')


print(Test2())  # output: pypi_url='https://pypi.org/'
print(Test2(pypi_url="notaurl"))  # raises ValidationError
```

This passes mypy checks on my end.

Mypy version - 0.942
Pydantic version - 1.9.0

Config from pyproject.toml:

```toml
[tool.mypy]
plugins = [
    "pydantic.mypy",
]
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
# https://pydantic-docs.helpmanual.io/mypy_plugin/#configuring-the-plugin
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```
