### ISSUE TITLE
Too many arguments for pydantic dataclasses using mypy

### ISSUE THREAD

**Issue by maddalab** [samuelcolvin/pydantic#2494]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8
            pydantic compiled: False
                 install path: /Users/bhaskar/Library/Caches/pypoetry/virtualenvs/relo-gcoUfTBT-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.7 (default, Jan 25 2021, 13:04:38)  [Clang 12.0.0 (clang-1200.0.32.28)]
                     platform: macOS-11.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I've looked up prior bug reports on the same issue that have been closed - at least one as fixed. One which provides a workaround by checking `TYPE_CHECKING`. However since I can reproduce the issue with a very basic use case I'm opening an issue hoping that the steps below make reproduction easy.

Prior reports
https://github.com/samuelcolvin/pydantic/issues/280
https://github.com/samuelcolvin/pydantic/issues/781

I've a simple pydantic dataclass

```python
@dataclass
class Config:
    name: str
    env: str
    group: str
    prefix: str
    task: str
```
and an equally simple initialization
```python
Config("c1", "prd", "grp", "pre", "tsk")
```

with `mypy` via `pre-commit`

```
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
```
and `pydantic` version `1.8`

```shell
poetry show pydantic
name         : pydantic
version      : 1.8
description  : Data validation and settings management using python 3.6 type hinting

dependencies
 - typing-extensions >=3.7.4.3
 ```

I get the error
```
Too many arguments for "Config"
```

**Comment by PrettyWood** [comment]
Hi @maddalab 
You should use the [mypy plugin](https://pydantic-docs.helpmanual.io/mypy_plugin/#generate-a-signature-for-dataclasses) ;)

**Comment by maddalab** [comment]
Thanks @PrettyWood 

Leaving a note for the next person who comes here. For pre-commit add the pydantic mypy plugin via `additional_dependencies`

```
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
            additional_dependencies:
                - pydantic
```

The configuration for the plugin is in the docs on the same link as provided above.
