### ISSUE TITLE
`pydantic-mypy` plugin is incompatible with `pyproject.toml` config in `mypy>0.900`

### ISSUE THREAD

**Issue by jrwalk** [samuelcolvin/pydantic#2895]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
pydantic version: 1.8.2
pydantic compiled: True
   install path: /opt/venv/lib/python3.8/site-packages/pydantic
   python version: 3.8.5 (default, Sep 10 2020, 16:58:22)  [GCC 8.3.0]
       platform: Linux-5.10.25-linuxkit-x86_64-with-glibc2.2.5
optional deps. installed: ['typing-extensions']
```

The newest release of `mypy` (0.900-0.901) has introduced `pyproject.toml` configuration in addition to the older `mypy.ini` in accordance with PEP-518. However, the `pydantic-mypy` plugin still expects an INI-formatted config file, such that TOML-configured mypy with the plugin enabled results in a parse error:

```py
Error constructing plugin instance of PydanticPlugin

Traceback (most recent call last):
  File "/opt/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/opt/venv/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 98, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 229, in _build
  File "mypy/build.py", line 475, in load_plugins
  File "mypy/build.py", line 453, in load_plugins_from_config
  File "pydantic/mypy.py", line 77, in pydantic.mypy.PydanticPlugin.__init__
  File "pydantic/mypy.py", line 114, in pydantic.mypy.PydanticPluginConfig.__init__
  File "/usr/local/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'pyproject.toml'
        [line 12]: ']\n'
        [line 17]: ']\n'
        [line 65]: ']\n'
...
```

Note that the plugin still works in `mypy>0.900` provided an INI configuration file is still provided. To bring the plugin up to speed for the newest mypy releases I believe we'll need a TOML parser option in addition to the default `ConfigParser` in the plugin constructor.

**Comment by johnthagen** [comment]
Should also update the user guide to show how to enable and configure the plugin for `pyproject.toml`. This will likely be what a vast majority of users will migrate to given how popular using `pyproject.toml` is becoming:

https://pydantic-docs.helpmanual.io/mypy_plugin/#enabling-the-plugin
https://pydantic-docs.helpmanual.io/mypy_plugin/#configuring-the-plugin

**Comment by jrwalk** [comment]
@johnthagen yep, I've got that in a PR I'm working on!

**Comment by johnthagen** [comment]
@jrwalk Upon further testing, the pydantic plugin does seem to be working at a basic level out of the box on a miniaturized example:

```py
# main.py
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, NoneStr


class Model(BaseModel):
    age: int
    first_name: str = 'John'
    last_name: NoneStr = None
    signup_ts: Optional[datetime] = None
    list_of_ints: List[int]


m = Model(age=42, list_of_ints=[1, '2', b'3'])
Model()  # will raise a validation error for age and list_of_ints
```

``` 
mypy main.py
main.py:15: error: Missing named argument "age" for "Model"
main.py:15: error: Missing named argument "list_of_ints" for "Model"
Found 2 errors in 1 file (checked 1 source file)
```

```toml
[tool.mypy]
ignore_missing_imports = true
strict = true

# Enable pydantic mypy plugin.
plugins = ["pydantic.mypy"]

# These configurations do not seem to be read:
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

```
pip list
Package           Version
----------------- --------
click             8.0.1
mypy              0.902
mypy-extensions   0.4.3
pep517            0.10.0
pip               21.1.2
pip-tools         6.1.0
pydantic          1.8.2
setuptools        57.0.0
toml              0.10.2
typing-extensions 3.10.0.0
```

`mypy` has a hard dependency on `toml` now, so that can be assured to be installed.

**Comment by jrwalk** [comment]
Interesting - I wonder if that's trying to parse the toml file through `ConfigParser` (expecting INI syntax) and just happening to not hit syntax errors. In my test case the array fields (e.g. `plugins`) included newlines, which is valid TOML but broke in INI syntax. Judging by that error, I wonder if it's not correctly loading the plugin at all.

Adding the toml config reader is straightforward since we can piggyback off `mypy`'s own logic for determining the config file - only trick is the tests need a little updating since we'd need to bump the test dependency to `mypy>0.900`, which had some formatting changes on the output.

**Comment by johnthagen** [comment]
> In my test case

It would probably be good to post your `pyproject.toml` here so a known failure case is documented.

**Comment by jrwalk** [comment]
@johnthagen maybe moot since the PR is open, but

**Comment by jrwalk** [comment]
```toml
[tool.mypy]
ignore_missing_imports = true
strict = true

# Enable pydantic mypy plugin.
plugins = [
  "pydantic.mypy"
]

# These configurations do not seem to be read:
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

should reproduce.

**Comment by hoefling** [comment]
Reading the config will fail as soon as TOML-specific stuff is present in `pyproject.toml`. E.g. adding
```toml
[[tool.mypy.overrides]]
module = "main"
no_implicit_reexport = true
```
or similar should already be enough to break the `ConfigParser`.
