### ISSUE TITLE
[Question]Is 'allOf' supported by Pydantic?

### ISSUE THREAD

**Issue by bquestions** [samuelcolvin/pydantic#478]
# Question

For bugs/questions:
* OS: CentOS 7.5
* Python version: 3.6.0
* Pydantic version: 0.19

Does pydantic currently support polymorphism/inheritance using`allOf`? For example if I have the following code (taken from https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#models-with-composition):

```py
from pydantic import BaseModel, Schema

def Error(BaseModel):
    message: str = Schema(..., description="")
    code: int = Schema(..., description="")

def ExtendedErrorModel(Error):
    rootCause: str= Schema(..., description="")
```

If I were to generate the schema for `ExtendedErrorModel` I should get something that matches the following which uses `allOf` to signify that if I'm creating an `ExtendedErrorModel` object, it not only specifies `rootCause` but also `code and message` :
```yaml
components:
  schemas:
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
```

However when it's actually generated, everything is flattened so the properties from the `ErrorModel` appear regularly on the `ExtendedErrorModel`. Which is how it should validate it, but not how the OpenAPI schema should appear:
```yaml
components:
  schemas:
    ErrorModel:
      type: object
      required:
      - message
      - code
      - rootCause
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
        rootCause:
          type: string
```
